name: Auto draft PR

on:
  push:
    branches-ignore:
      - master
      - '**/gh-readonly-queue/**'
    tags-ignore:
      - '**'

jobs:
  draft-pr:
    uses: jtl-software/actions/.github/workflows/auto-draft-pr.yaml@fba69471aba7cfd1a555a47c5dc9572ccd510d53 # v1.0.0
