name: Check

on:
  push:
    branches: [master]
  pull_request:

jobs:
  status-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      packages: read
    container:
      image: ghcr.io/jtl-software/connector-utils-ci-docker/php/cli:8.3
      options: --user root
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: git config --global --add safe.directory '*'

      - run: composer install --no-progress --no-interaction
      - run: composer global require "staabm/annotate-pull-request-from-checkstyle:^1.8"

      - name: PHPCS
        if: always()
        run: bash .github/scripts/run-phpcs.sh

      - name: PHPStan
        if: always()
        run: composer run phpstan -- --error-format=github

  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      - name: Composer install
        run: composer install --no-interaction --no-progress

      - name: PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml --bootstrap vendor/autoload.php --log-junit junit.xml

      - name: Upload JUnit results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: junit-php-${{ matrix.php-version }}
          path: junit.xml
          retention-days: 7
